### ISSUE TITLE
Prediction c++ service example

### ISSUE THREAD

**Issue by jakeju92** [speshowBUAA/mmdet3d_onnx_tools#2]
Hi @speshowBUAA,

Thanks for creating this repo to convert pointpillars pth file to onnx file. I was wondering if you could provide an example of the c++ inference engine code as well. Or, could you recommend me another repo that I can refer to? Thanks again for your amazing work!

**Comment by jakeju92** [comment]
Just found your c++ inference repo: https://github.com/speshowBUAA/mmdet_pp 
Bravo! What are the prerequisites for that repo? What version do you use for TRT,  CMAKE, C++, ROS, Ubuntu version, etc.? Thanks!

**Comment by speshowBUAA** [comment]
jetpack 4.5.1  cuda 10.2 tensorrt 7.1.3 cuDNN 8.0.0 CMAKE 3.17.5
ubuntu 16.04+ROS kinetic and ubuntu18.04+ROS melodic both works.

**Comment by jakeju92** [comment]
Thanks for your reply!
